image: docker

stages:
  - build

before_script:
  - apt-get update -yqq
  - apt-get install -yqq apt-transport-https ca-certificates curl gnupg2 software-properties-common lsb-release
  - lsb_release -cs
  - echo "Adding SBT repository"
  - apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 2EE0EA64E40A89B84B2DF73499E82A75642AC823
  - echo "deb http://dl.bintray.com/sbt/debian /" | tee -a /etc/apt/sources.list.d/sbt.list
  - echo "Adding Docker repository"
  - curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add -
  - add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable"
  - apt-get update -yqq
  - apt-get install -yqq sbt
  - apt-get install -yqq docker-ce docker-ce-cli
  - sbt sbtVersion
  - docker version

build:
  stage: build
  services:
    - docker:dind
  script:
    - sbt clean test docker:publish
