image: docker

stages:
  - build

before_script:
  - apk add openjdk8 sbt --update-cache --repository http://dl-cdn.alpinelinux.org/alpine/edge/testing
  - sbt sbtVersion
  - docker version

build:
  stage: build
  services:
    - docker:dind
  script:
    - sbt clean test
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - sbt docker:publish
