image: openjdk:11-jdk

stages:
  - test
  - build

before_script:
  - apt-get update -yqq
  - apt-get install apt-transport-https -yqq
  - echo "deb http://dl.bintray.com/sbt/debian /" | tee -a /etc/apt/sources.list.d/sbt.list
  - apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 2EE0EA64E40A89B84B2DF73499E82A75642AC823
  - apt-get update -yqq
  - apt-get install sbt -yqq
  - sbt sbtVersion

test:
  stage: test
  script:
    - sbt clean test

build:
  stage: build
  services:
    - docker:dind
  script:
    - apt-get update -yqq
    - apt-get install -yqq apt-transport-https ca-certificates curl gnupg2 software-properties-common
    - curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add -
    - add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable"
    - apt-get update
    - apt-get install -yqq docker-ce docker-ce-cli cointainerd.io
    - sbt docker:publish
