image: docker

stages:
  - build

before_script:
  - apk add sbt --update-cache --repository http://dl-cdn.alpinelinux.org/alpine/edge/testing
  - sbt sbtVersion
  - docker version

build:
  stage: build
  services:
    - docker:dind
  script:
    - sbt clean test docker:publish
